### ISSUE TITLE
Missing data when converthing certain files.

### ISSUE THREAD

**Issue by Zer0XoL** [jam1garner/aamp2xml#1]
Hello, we have been messing around with this tool and we noticed some files result in:
<?xml version="1.0" encoding="utf-8"?>
<param_root type="Boolean">0</param_root>

When you can see in Wexos toolbox that certain things are there.
For example 
[Enemy_Bee_Swarm.bchemical.txt](https://github.com/jam1garner/aamp2xml/files/1399129/Enemy_Bee_Swarm.bchemical.txt)
Seem to contain data that is not visible in the resulting XML file.

Thank you.

**Comment by jam1garner** [comment]
I'm already aware and have no intentions to fix this. If you want it fixed submit a PR.

**Comment by Zer0XoL** [comment]
Noted. Could you point me in the right direction? Like what in general is causing it?
Thanks.

**Comment by jam1garner** [comment]
Uhhh if I remember correctly it is because there is a second type of node that has a bit more information and can point to either the original type of nodes, the second type of node or a combination of both. I had no really good solution for differentiating them in XML aside from adding something to the tag and I didn't really want to rewrite the format specification. If you look at the information [in this documentation file (relevant lines linked)](https://github.com/jam1garner/aamp2xml/blob/master/AAMP_docs.txt#L17-L22), you can see the root nodes which there is always 1 at the beginning of the file but I don't handle if there is more that stem off of the root node.

**Comment by Zer0XoL** [comment]
Thank you for the help.
I was just wondering, how did you extract the names that are hashed with crc32 from U-king.rpx?
I was thinking of extracting from other files as well.
Thanks.

**Comment by jam1garner** [comment]
Either use IDA + Wii U loader plugin -> strings subview -> dump strings or use rpx2elf then dump strings using any tool of your choice
